### ISSUE TITLE
Events only trigger for last added minut point

### ISSUE THREAD

**Issue by ketra** [ketra/nl.ketra.point#33]
Only the lastly added minut point reacts to the events. this needs to be fixed.

**Comment by ketra** [comment]
The function for the webhook handler needs to be changed from device to other file. and given access to all devices.

**Comment by MP-ICT-Diensten** [comment]
`mpietersma@mp-pi02:~/homey/nl.ketra.point$ homey app run
✓ Pre-processing app...
✓ Validating app...
Warning: drivers.Point is missing an array 'energy.batteries' because the capability measure_battery is being used. Specifying the type of battery will be required in the future.
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
 — App size: 8.39 MB
✓ Installing Homey App on `Homey KD71` (http://192.168.10.221:80)...
✓ Homey App `com.ketra.point` successfully installed
✓ Running `com.ketra.point`, press CTRL+C to quit
 — Profile your app's performance at https://go.athom.com/app-profiling?homey=5a4cfae22d37656f41d5366e&app=com.ketra.point
─────────────── Logging stdout & stderr ───────────────
module.js:550
    throw err;
    ^

Error: Cannot find module './definition_schema'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/ajv/lib/keyword.js:5:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

--- INFO: com.ketra.point has been killed ---

`

**Comment by ketra** [comment]
@MP-ICT-Diensten this happens when an old version is being installed after upgrading to 1.0.0, due to the changed for energy support.

**Comment by MP-ICT-Diensten** [comment]
@Ketra is this git then not updated?  Because I made a clone of the source here, change to branch OauthDriver_implement and tried that version.

**Comment by MP-ICT-Diensten** [comment]
Results from the past day's, looking good.

![Minut responses](https://user-images.githubusercontent.com/28575285/71763883-945f1500-2ee1-11ea-80c1-8c7553b3af5a.png)

**Comment by MP-ICT-Diensten** [comment]
Solved (in 1.0.5 at least)
